server:
  port: ${PORT:8080}

spring:
  application:
    name: vc
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5469/nobinden}
    username: ${DATABASE_USERNAME:nobinden}
    password: ${DATABASE_PASSWORD:password}
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true
    locations: classpath:db/migration
    validate-on-migrate: false
    baseline-on-migrate: true
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

resend:
  api-key: ${RESEND_API_KEY:}

notification:
  recipient: ${NOTIFICATION_RECIPIENT:kenodeary3@gmail.com}