server:
  port: 8081

spring:
  application:
    name: vc
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5469/nobinden
    username: nobinden
    password: password

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none

  flyway:
    enabled: true
    locations: classpath:db/migration
    validate-on-migrate: false
    baseline-on-migrate: true