CREATE TABLE IF NOT EXISTS application
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name                 VARCHAR(255),
    sector               VARCHAR(255),
    founder_email        VARCHAR(255),
    founder_phone_number VARCHAR(255),
    target_round         VARCHAR(255),
    deck_url             VARCHAR(255),
    additional_comments  VARCHAR(255),
    status               VARCHAR(255),
    submitted_at         TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_application PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS application_founders
(
    application_id BIGINT NOT NULL,
    founder_name   VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS funding_by_round
(
    startup_id BIGINT       NOT NULL,
    amount     DOUBLE PRECISION,
    round_name VARCHAR(255) NOT NULL,
    CONSTRAINT pk_funding_by_round PRIMARY KEY (startup_id, round_name)
);

CREATE TABLE IF NOT EXISTS partner
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255),
    role VARCHAR(255),
    CONSTRAINT pk_partner PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS startup
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(255),
    sector          VARCHAR(255),
    series          VARCHAR(255),
    eval            DOUBLE PRECISION, -- Ensure this exists!
    equity          DOUBLE PRECISION,
    funds_accrued   DOUBLE PRECISION,
    projected_close DATE,
    stage           VARCHAR(255),
    partner_id      BIGINT REFERENCES partner (id)
);

CREATE TABLE IF NOT EXISTS startup_founders
(
    startup_id   BIGINT NOT NULL,
    founder_name VARCHAR(255)
);

ALTER TABLE startup
    ADD CONSTRAINT FK_STARTUP_ON_PARTNER FOREIGN KEY (partner_id) REFERENCES partner (id);

ALTER TABLE application_founders
    ADD CONSTRAINT fk_application_founders_on_application FOREIGN KEY (application_id) REFERENCES application (id);

ALTER TABLE funding_by_round
    ADD CONSTRAINT fk_funding_by_round_on_startup FOREIGN KEY (startup_id) REFERENCES startup (id);

ALTER TABLE startup_founders
    ADD CONSTRAINT fk_startup_founders_on_startup FOREIGN KEY (startup_id) REFERENCES startup (id);